### ISSUE TITLE
Planning a GUI version?

### ISSUE THREAD

**Issue by cartersremasters** [yyang181/BiSTNet#3]
I am pretty damn stupid when it comes to coding, etc, but I do love colorizing, and have been doing it for some time, I have been using DeepRemaster, and have been growing disappointed by the results, would love to test this out!

colorization using Modified DeepRemaster https://www.youtube.com/watch?v=LfgvoNvjRFY

**Comment by yyang181** [comment]
Hi, thanks for your question. Regarding your request for our coloring algorithm GUI version, we are currently planning to implement this feature with Huggingface in June of this year. Once we developed the web-gui, we would be happy to share it with you. Thanks for your patience and understanding.
